Scrooge: Fix SBT Publish Build
**Problem**
Currently the sbt build fails with the following error

```
 (scrooge-thriftValidation / publishM2) java.io.IOException: PUT operation failed because the destination file exists and overwriting is disabled:
Error:      source     : /home/runner/.dodo/clones/scrooge/scrooge-thrift-validation/target/scala-2.10/scrooge-thriftvalidation_2.10-24.2.0.pom
Error:      destination: file:/home/runner/.m2/repository/com/twitter/scrooge-thriftvalidation_2.10/24.2.0/scrooge-thriftvalidation_2.10-24.2.0.pom
Error:  If you have a staging repository that has failed, drop it and start over.
Error:  Otherwise fix the double publishing, or relax the setting as follows:
Error:      publishConfiguration := publishConfiguration.value.withOverwrite(true)
Error:      publishLocalConfiguration := publishLocalConfiguration.value.withOverwrite(true)
Error:
Error:  If you have a remote cache repository, you can enable overwriting as follows:
Error:      pushRemoteCacheConfiguration := pushRemoteCacheConfiguration.value.withOverwrite(true)
```

**Solution**
Try setting it as snapshot to allow overwrites and set overwrite as true to remote repos

Differential Revision: https://phabricator.twitter.biz/D1141310